run tests on make check (or make test)

diff --git a/testing/run b/testing/run
--- a/testing/run
+++ b/testing/run
@@ -23,12 +23,20 @@ colournul () {
 
 
 cd "$(dirname "$0")"
+declare -i failures=0
 for xml in *.xml; do
     test=${xml%%.xml}
     rm -f "$test.{output,bin}"
-    (
-	../lrx-comp "$test.xml" "$test.bin" &>>>(err "$test") &&
-	../lrx-proc -z "$test.bin" < "$test.input" > "$test.output" 2>>>(err "$test") &&
-	diff -au "$test.expected" "$test.output" | colournul
-    ) || echo "$test: FAILED"
+    if ! (
+            ../lrx-comp "$test.xml" "$test.bin" &>>>(err "$test") &&
+                ../lrx-proc -z "$test.bin" < "$test.input" > "$test.output" 2>>>(err "$test") &&
+                diff -au "$test.expected" "$test.output" | colournul
+        )
+    then
+        echo "$test: FAILED"
+        (( failures++ )) || true
+    fi
 done
+if [[ $failures -gt 0 ]]; then
+    exit 1
+fi
