tests for issue #3 – and found a case not yet fixed in 5d06817543882cdbf17fbbf16d7c99ae3ebd29ce

diff --git a/testing/run b/testing/run
--- a/testing/run
+++ b/testing/run
@@ -33,8 +33,12 @@ for xml in *.xml; do
                 diff -au "$test.expected" "$test.output" | colournul
         )
     then
-        echo "$test: FAILED"
-        (( failures++ )) || true
+        if [[ "${test}" = issue3-prefix ]]; then
+            echo "$test: FAILED (expected, TODO)"
+        else
+            echo "$test: FAILED"
+            (( failures++ )) || true
+        fi
     fi
 done
 if [[ $failures -gt 0 ]]; then
